### PR TITLE
add a `main` property in package.json to support yarn

### PR DESCRIPTION
**Pull request by felix-starman**
re-adds the `main` property and points it to the ES6 module.

[yarn](https://yarnpkg.com/) follows the [package.json](https://docs.npmjs.com/cli/v7/configuring-npm/package-json) docs fairly strictly and was unable to import the `phoenix_live_view` JS module. By adding this property back in, we should be able to support other environments that don't use `npm` to resolve dependencies.

### CODE REVIEW

**Comment by felix-starman** [comment]
We can make a repo to reproduce if that would be helpful. Please let us know if that would be preferred

**Comment by mcrumm** [comment]
Hi @felix-starman – can you tell us what version of yarn you are running?

I am currently using yarn v1.22.10 at my day job without issue, so my best guess is that issue may be affecting v2/v3?

**Comment by felix-starman** [comment]
hey @mcrumm 
We're running yarn 2.4.2

**Comment by felix-starman** [comment]
dangit, sorry, I'll rebase this instead tomorrow

**Comment by josevalim** [comment]
:green_heart: :blue_heart: :purple_heart: :yellow_heart: :heart:

**Pull request merged**
