### PR TITLE
Add navigation guards to liveSocket

### LINKED ISSUE #2107: scroll other element than body on history navigation
Currently, the scroll position for the body element is retained and restored on history navigation.

My specific use case is "prevent iOS overscroll", which is usually done by giving the body the height of the viewport, then wrapping all scrollable content in another div. I am aware that `overscroll-behavior: contain` supposedly fixes that in iOS 16, but at least in iOS 15 it won't work even with the experimental feature flag for this toggled on. 

I guess there might be other use cases that scroll an element besides `body`, or maybe even have multiple scroll positions.

My initial attempt was to add my own `scroll` and `popstate` listeners, and modify the history state by adding my own attribute. This works in some cases, but there are edge cases left when navigating without another scroll event. During navigation the history state is rewritten by live view, removing my previously stored extra scroll position. I haven't fully understood why this happens, though I believe it's not due to a race condition with other scroll related code that gets delayed through `requestAnimationFrame` or `setTimeout(…, 0)`. Even if I were to make that work, this approach more or less relies on live view working in an implicit way, rather than on a proper interface.

In terms of solutions, I can think of these approaches:
1. make the element on which LiveView restores the scroll position configurable
2. hooks/callbacks for client side code to store additional info into the history object and also one for `popstate` after LiveView did its thing
3. re-store scroll position of all elements, or at least ones with a `phx-restore-scroll` attribute or similar
4. store scroll positions outside of the history object, but with enough info to exactly match the pages in the forward/backward history (i.e. store the full state, not just the URL). This can be done on the server or client, as long as either one of them has all the information necessary for matching.

1 is easy but also very specific to my use case and doesn't generalize well.
2 would be powerful enough, but adding my own "workaround code" and generally writing more JS doesn't seem to match the intention of LiveView in general. 
3 might be decent enough if limited to elements with an `id` attribute (+ special treatment for `body`). Having this to configure this at all strikes me as a downside though, since ideally I wouldn't have to think about scroll position restoring at all and navigating would "just restore all scroll positions"
4 sounds like duplication of state is necessary, or at least it'd require sending scroll events to the server. This seems a bit brittle and overkill at the same time.

Potentially some special handling for regular live_patching is required, too. If one of the "to be scrolled/restored" elements changes its contents, it will retain the scroll position. This is not what browsers do, and also a problem in my specific case (I exchange the article/text content this way, and it's rather unlikely a user wanting to starting reading a long from text from the middle). My current fix is a `phx-hook` that sets `elem.scrollTop = 0`, which I guess should be solved by any implementation. At the very least, there should be a defined way to ensure that these hooks are not racy with the scroll restoration implemented in LiveView itself.

Of all the approaches I mentioned, my guess is 3 is the least-worst. Naming will be tough if `phx-restore-scroll` also _resets_ scroll when using regular/non-history live_patch navigation. Doing it for all elements that have an `id` and receive a scroll event might also work, but has the surprising side-effect that the scroll behaviour changes when this attribute is added/removed. Given that it's _probably_ not a common issue, I'd rather go for opt-in because that can be searched for in the documentation.

I'm happy to work on this because this annoys me to a greater deal than I am willing to admit. Given the unclear trade-off situation, I am hoping a second pair of eyes can provide a better suggestion.

### PR DESCRIPTION
**Pull request by SteffenDE**
This PR introduces a new option that can be specified when creating a livesocket instance: `navigation`. It is inspired by [navigation guards in SPA routers](https://router.vuejs.org/guide/advanced/navigation-guards.html) like Vue Router.

`navigation` is an object that can define two functions: `beforeEach` and `afterEach`. The `beforeEach` function is called before each navigation event and can for example be used to store custom scroll positions. If the `beforeEach` function returns `false`, the navigation will be aborted. This can be used to implement a warning when the user tries to navigate while a form is still being edited. The `afterEach` function is called after a navigation event has been completed. It can be used to restore the scroll position that was stored in the `beforeEach` function.

Example to restore a custom scroll position:

```javascript
let liveSocket = new window.LiveView.LiveSocket("/live", Socket, {
    params: {_csrf_token: csrfToken},
    navigation: {
        beforeEach(_to) {
            if(document.querySelector("#my-scroll-container")) {
                customScrollPosition = document.querySelector("#my-scroll-container").scrollTop
            }
        },
        afterEach(_to) {
            if (document.querySelector("#my-scroll-container")) {
                document.querySelector("#my-scroll-container").scrollTop = customScrollPosition
            }
        }
    }
})
```

Example to prevent navigation when a form submit is pending. This example assumes that the form has a custom attribute, that could be set in a `phx-change` handler:

```javascript
let liveSocket = new window.LiveView.LiveSocket("/live", Socket, {
    params: {_csrf_token: csrfToken},
    navigation: {
        beforeEach(_to) {
            if(document.querySelector("form[data-submit-pending]")) {
                return confirm("Do you really want to leave the page?")
            }
        }
    }
})

window.onbeforeunload = function(e) {
    if(document.querySelector("form[data-submit-pending]")) {
        return "Do you really want to leave the page?"
    }
};
```

Fixes #2107.

This PR should not be accepted in the current state, but instead just show the idea and maybe discuss how such an API could be optimized, if this is something that we want.

### CODE REVIEW

**Comment by SteffenDE** [comment]
Events could probably work for the scroll restoration use case, but for preventing navigation this needs to happen synchronously. I guess we could move the actual navigation itself to an event listener and then let users prevent it by calling stopPropagation?

**Comment by josevalim** [comment]
Oh, good call on being synchronous. Yeah, for me that justifies the difference. :) TY!

**Comment by chrismccord** [comment]
This interface makes sense and it also gives folks a place to perform [view transitions](https://developer.mozilla.org/en-US/docs/Web/API/View_Transitions_API). Perhaps we also want the callback to support an async interface as well?

**Comment by SteffenDE** [comment]
View transitions are interesting indeed. I'll try to adapt the PR to also allow returning a promise from the callbacks later today. How would the usage with view transitions look like?

```javascript
let liveSocket = new window.LiveView.LiveSocket("/live", Socket, {
    params: {_csrf_token: csrfToken},
    navigation: {
        beforeEach(_to) {
            return new Promise((resolve) => document.startViewTransition(() => resolve()));
        }
    }
})
```

What I'm still thinking about is the parameters. Probably we want to pass both the old and new route in the callbacks. Do you have any opinion which format would be the best? (Currently I simply use the href string)

**Comment by SteffenDE** [comment]
I changed to callbacks to `beforeEach(from, to)` and `afterEach(from, to)`. Both parameters get passed the full href string and both can now return promises as well.

Next step: add some tests.

**Comment by SteffenDE** [comment]
Still missing: documentation

**Comment by SteffenDE** [comment]
You can have a look at view transitions in action: just run `npm run e2e:server` and visit http://localhost:4000/navigation/a. On Page B you can test the form confirmation.

**Comment by SteffenDE** [comment]
Docs done, ready for review and final touches.

**Comment by breunigs** [comment]
I believe this patch/approach is in general a good idea, but I don't think the provided example fixes #2107 fully. Consider these steps to reproduce:

1. I am on page A, scrolling `#element` to 500px
2. I click on a link leading to page B. Example stores `scrollPositions["element"] = 500`.
3. I click on a link leading to page A. Example restores `#element`'s scroll to 500px, even though I expected to be scrolled to the top (or some other `#anchor`). 

This issue goes away by storing the scroll state (or any other state for that matter) in the browser's history state, the same way LiveView already does for the body's scroll position:

```js
let state = history.state || {}
state.customElementScrollState = document.getElementById("customElement").scrollTop
history.replaceState(state, "", window.location.href)

// or reuse LV's Browser.updateCurrentState from LV code if that is reachable
```

Obviously, both app code and LiveView code now contest for the same namespace. This is an easy fix, by designating a well known key for either LV, or the user to put their own state, or potentially provide an API.

**Comment by SteffenDE** [comment]
That’s a very good point. I’ll try to adapt the API to incorporate the history state.

**Comment by breunigs** [comment]
I tested it in my real world project and the scroll restoration example now works with a 1:1 copy and paste (and setting the data attribute).

**Comment by breunigs** [comment]
After some further testing, I have found that the `userData` is not available on a browser forward button navigation. Here's a reproducer  that shows the issue: https://github.com/breunigs/liveviewtest1/commit/cc2fe66a88f03e7bf085a2f15d6ef44d46252091

1. setup the repo (`git  clone https://github.com/breunigs/liveviewtest1 && cd liveviewtest1 && mix deps.get && cd deps/phoenix_live_view/assets && npm install && cd .. && mix deps.get && mix assets.build && cd ../.. && mix phx.server`)
2. open `localhost:4000`
3. open the browser's dev tools, optionally filter by `nav` to show only reproducer's logs
4. click on the "goto page 2" link
5. observe that it saved the dummy user data for page1 and _correctly_ displays that there's no user data for this new page
6. use the browser's back button
7. observe that it saved the dummy user data for page2 and _correctly_ displays the saved dummy data
8. use the browser's forward button
9. observe that it _incorrectly_ shows user data as "undefined"

This is reproducible in Firefox and Chrome for me. In general, browsers do retain history state even on forward navigation, so this is not a browser limitation. I don't have a hunch why this happens with the PR (at least not yet).

**Comment by SteffenDE** [comment]
@breunigs this is sadly a limitation of the history API.

When you navigate to a new page, we save the userData in the "old" history state. The history is like a stack. So starting on page 1 and then navigating to page 2, the history looks like this (new entries on top):

```
{type: "patch", id: "phx-..."}
{type: "patch", id: "phx-...", userData: ...}
```

Note that on the new page, the userData is never set. If you now navigate back in the history, the userData is restored. The problem is that you cannot save new data when navigating back, because the browser only tells you that you navigated back after the navigation is already done.
If you navigate forward from page 1 to page 2 again, the empty state (on top above) is restored. So if you want to ensure that a scroll state is restored in any case, you would need to do something like LiveView does internally: proactively update the **current** history entry.

It is worth discussing if there should be an API to not need to manually change the history state. Something like

```
let scrollTimer
window.addEventListener("scroll", _e => {
  clearTimeout(scrollTimer)
  scrollTimer = setTimeout(() => {
    let scrollPositions = {}
    Array.from(document.querySelectorAll("[data-restore-scroll]")).forEach(el => {
      scrollPositions[el.id] = el.scrollTop
    })
    liveSocket.updateNavigationUserdata(data => Object.assign(data, {scrollPositions}))
  }, 100)
})
```

Maybe there should also be another parameter (?) in `beforeEach` that tells us if we are in a popstate situation `beforeEach(_to, _from, popped)`, because returning data does not really make sense in that case.

**Comment by SteffenDE** [comment]
I'll need to think about this a little more.

**Comment by breunigs** [comment]
Just for my understanding: so with your PR and me navigating back, the order of events is like this:
1. I click back
2. browser navigates back
3. browser informs LV (via popstate)
4. LV processes `navigation.beforeEach`
5. LV renders
6. LV processes `navigation.afterEach`
And obviously after step 3 we can't access the history entry we need to access?

If so, then I presume something like https://caniuse.com/mdn-api_navigation_navigate_event  would do the trick, but that API isn't even usable in all modern browsers, let alone the ancient ones LV still supports.

**Comment by SteffenDE** [comment]
> If so, then I presume something like https://caniuse.com/mdn-api_navigation_navigate_event would do the trick, but that API isn't even usable in all modern browsers, let alone the ancient ones LV still supports.

Yes, exactly.

**Comment by bcardarella** [comment]
@SteffenDE I don't want to derail you but have you looked into using the History API for this? I implemented this solution in EmberJS years ago. When pushing history onto the stack you can include state information, which I used to stuff the x,y scroll positions so when the state was popped off the stack and such state was available the scroll position was restored:

https://github.com/DockYard/ember-router-scroll/pull/14/files

**Comment by greven** [comment]
I have several multi page forms where one can navigate between steps, I explored a way to prevent data loss when clicking the steps but figured out it was impossible to prevent navigation since there isn't a hook on navigation. 

This would be a godsend for this layout pattern for sure. 👍

**Comment by SteffenDE** [comment]
There are a couple of issues with this:

1. There is no widely supported way to actually prevent navigations from happening. Therefore, things like a user pressing the back button cannot reliably be prevented at the moment. In the future, the navigation API will allow this, but browser support is still severely lacking.

2. We’d need to think about navigations that are triggered by the server. In particular, the LV process currently shuts down when anything but a patch is triggered, e.g. using `redirect(socket, …)` or `push_navigate(socket, ...)`.

All in all, I currently don't see an easy way forward here. I'd love to see a "do you really want to leave" functionality in LV and rest assured that this is still on our radar for after 1.0!

**Comment by bu6n** [comment]
The arguments advanced for closing this seem to be related to the "do you really want to leave" functionality. The first post was speaking about scroll positions also, which to me is a little bit different. Would there be a middle way enabling restoring scroll position? I would like to keep the scroll position of a sticky liveview on live navigation and right now this does not seem possible without flickering.

**Comment by SteffenDE** [comment]
@bu6n we‘re tracking the scroll position topic here: https://github.com/phoenixframework/phoenix_live_view/issues/2107

So no worries, it’s not forgotten :)

**Pull request closed without merging**
