### PR TITLE
Fix scroll restoration on native navigation

### PR DESCRIPTION
**Pull request by almielczarek**

### CODE REVIEW

**Comment by chrismccord** [comment]
Can you explain step by step what behavior you see vs how the scroll should behave? @jeregrine and I specifically walked thru scroll position and added the code that this removes to abide by browser behavior so we need more info here on what's not working. Thanks!

**Comment by almielczarek** [comment]
I figured you added that code for a good reason.

I opened an issue with more details, but Jose closed it - probably to move the discussion over here.

Here's what happens on master:
1. Load live view page
2. Click normal anchor (not a live_patch or live_redirect) tag on that page that causes the current page to be unloaded
3. Click browser back button to return to live view page
4. Original live view page is loaded, but scroll position is lost

Removing only the line referenced in this pull request changes the behavior to this:
1. Load live view page
2. Click normal anchor (not a live_patch or live_redirect) tag on that page that causes the current page to be unloaded
3. Click browser back button to return to live view page
4. Original live view page is loaded with last scroll position

Someone else who has run into what I believe is the same issue posted a comment here: https://elixirforum.com/t/how-to-restore-scroll-position-in-live-view-app/31548/9

If you'd like a repo with an example before and after this change I'd be happy to make one.

**Comment by almielczarek** [comment]
Here's the issue: https://github.com/phoenixframework/phoenix_live_view/issues/1255

**Comment by chrismccord** [comment]
I see, so it sounds like it is only an issue from LV => regular anchor => non LV. This PR breaks the LV <=> LV scroll position, so it needs more work to accommodate this scenario. We may need to intercept non LV anchors and change the scroll history behavior there, but I'm not entirely sure how browsers will behave. Is this something you can look into? Thanks!

**Comment by almielczarek** [comment]
I'd be happy to look into it! I had a bit of a hacky solution involving a beforeunload event handler close to working while I was investigating before. I'll see if I can get it working properly.

**Comment by almielczarek** [comment]
Just so I know what exactly not to break, when you say LV <=> LV, do you mean live_patch/live_redirect and friends?

**Comment by chrismccord** [comment]
yes exactly, `live_redirect` and back/forward pop state b/w live redirects

**Comment by almielczarek** [comment]
I wish I could have gotten around to this a bit earlier. I wanted to get a better grasp on the internals of live view.

I believe this leaves the existing functionality in tact while fixing the issue outlined above.

If you see anything that looks incorrect or changes the project in a way you disagree with I'd be glad to change it.

**Comment by cw789** [comment]
@almielczarek
This is not a critic to your solution. Testing it quickly it seems to solve the issue.

Only about if it's ok to use the click event for scroll restoration I'm in doubt...
I think a navigation behavior doesn't mean it must have fired click event. But I could be wrong.

**Comment by Abat** [comment]
@almielczarek any updates on this? This bug is a bit annoying, would be great to have it merged

**Comment by almielczarek** [comment]
I have from Thursday through Sunday to focus on this. Shouldn't take that long, but I want to make sure I'm not creating more issues for anyone.

I'd expect to have a better solution soon.

**Comment by c4710n** [comment]
I met this problem too. And, I noticed the label on this PR, so I want to share my trace when solving this problem.

## The demo project

https://github.com/dodrio/phx-live-demo

## Preface
### 3 types of page navigating
There're 3 types of page navigating when using LiveView:

+ LV -> LV
+ LV -> NORMAL VIEW
+ NORMAL VIEW -> LV

> NORMAL VIEW means the page without using LiveView.

### scroll restoration
It is a browser's behaviour which will restore the scroll position when the user triggers popstate event.

This event can be triggred by:

+ a click on the back or forward button of browser UI.
+ calling `history.back()` or `history.forward()` in JavaScript.

> But now,  LiveView is using a implementation provided by its own.

## Reproduce The Problem

1. Open the LiveView page - `http://localhost:4000/`.
2. Scroll the page a little bit, and click **GOTO NORMAL DOC**.
3. Click **BACK BUTTON of browser**(not the button on page) to return the LiveView Page.
4. LiveView Page is loaded, **but the scroll position is lost**.

This problem appears when navigating from LV to NORMAL VIEW, but doesn't appear when:

- LV -> LV
- NORMAL VIEW -> LV

## Analyze The Problem

### LV -> LV

> Everything is fine.

The history is totally managed by the JS provided by LiveView.

> After LiveSocket connected, [`history.scrollRestoration` will be set to `"manual"`](https://github.com/phoenixframework/phoenix_live_view/blob/1471909fbd49990c09275fc32988c2e6f3613087/assets/js/phoenix_live_view/live_socket.js#L545).

### NORMAL VIEW -> LV

> Everything is fine.

In NORMAL VIEW, LiveSocket doesn't connect at all, so `history.scrollRestoration` will remain the default value - `"auto"`, which makes scroll restoration worke as expected.

### LV -> NORMAL VIEW

> Something wrong here.

As we mentioned above:

1. After LiveSocket connected, `history.scrollRestoration` will be set to `"manual"`
2. Then, Phoenix LiveView manages the browser's history by its own.

**The problem is that Phoenix LiveView only handle the scroll restoration for `live_patch` and `live_redirect`, the raw `<a>` tag is not taken into account.**

## A Possible Solution

1. I have found a related commits in Phoenix LiveView. - https://github.com/phoenixframework/phoenix_live_view/commit/f1e614e9ab6d6b16192ab516240a540857c3eec9 . The core code is:
```js
// part1
if(history.scrollRestoration){ history.scrollRestoration = "manual" }

// part2
let scrollTimer = null
window.addEventListener("scroll", _e => {
  clearTimeout(scrollTimer)
  scrollTimer = setTimeout(() => {
    Browser.updateCurrentState(state => Object.assign(state, {scroll: window.scrollY}))
  }, 100)
})
```
2. Above commit is trying to solve something called **Fix 0 scroll and record current scroll position to restore forwards**. Then, I want to find out what the problem - **0 scroll** is. So I reverted changes by above commit  manually.
3.  At first time, I removed part1, everything was fine. Scroll restoration works in all situations:
    + (works) LV -> LV 
    + (works) LV -> NORMAL VIEW 
    + (works) NORMAL VIEW -> LV
4. At second time, I removed part2. The scroll restoration broke when clicking **forward button of browser** - the scroll position is not right.

In my rudimentary experiment, It seems that `history.scrollRestoration = "manual"` is not required. What if we just following this line?
```diff
- if(history.scrollRestoration){ history.scrollRestoration = "manual" }
```

@chrismccord May be you can give use more insight about this? Thanks in advance.

**Comment by almielczarek** [comment]
Hey, @c4710n

You're correct that leaving history.scrollRestoration set to auto fixes navigation from LV back to a normal page. I'm doing that as a workaround with one of my work projects right now, and it seems to be doing the trick.

Chris mentioned earlier that doing so will break navigation between live views, but I haven't seen it happen yet with my project. It is entirely possible that he's talking about other browsers or I'm missing something else. I'm in a setting where most people are using Chrome.

I also tried in the most recent commit for this PR to listen for anchor clicks and store scroll position to be restored on navigation as well, and that seems to work in Chrome, but I'm not sure about other browsers, or in other scenarios (non-live view JS navigation, etc).

I'm wondering if we can put `history.scrollRestoration = "manual"` behind an if statement that checks if there is a scroll position to be restored on page load, rather than doing it for every page load.

We'd be effectively only taking control away from the browser when we need to, rather than taking it away everywhere and having to essentially reprogram what the browser already knows how to do.

I'll throw together another commit with this implemented. If anyone has any other ideas, I'd love to hear them.

**Comment by tomtaylor** [comment]
I've just been bitten by this. Setting `history.scrollRestoration` to `auto` fixes normal `<a>` links from LiveView components to external pages, but it would be good to have this fixed in LiveView itself. Can I help make progress on landing this PR or a similar solution?

**Comment by chrismccord** [comment]
This has been long stale so closing until we have further movement. Note that the proposed fixes need to work for both native -> LV and LV <-> LV. This PR appears to sacrifice the latter. Thanks!

**Pull request closed without merging**
