### PR TITLE
Use phash2 for computing fingerprint

### PR DESCRIPTION
**Pull request by dvic**

### CODE REVIEW

**Comment by dvic** [comment]
This should be a bit faster and avoid previously made allocations to compute the MD5 digest (i.e., the call to `term_to_binary`).

**Comment by josevalim** [comment]
Unfortunately there is no documentation on the function in regards to collisions. Usually when hashing for a hash dict or similar, we use the hash to find a bucket and then check for collisions, but in our case we don’t check for collisions and therefore it is important the algorithm we use guarantees low collision.

The fact it uses less than a half bits than MD5 is not a good sign either. :)

**Comment by josevalim** [comment]
There are many used cases where phash2 is great though, such as routing, partitioning, or when you do collision detection, this is not one of them though :)

**Comment by dvic** [comment]
Clear, thanks for the explanation 👍

**Comment by josevalim** [comment]
If you wanna Submit A pull request that adds some code comments explaining our usage of MD5, then I think it can be helpful to future code readers :)

**Pull request closed without merging**
