### PR TITLE
Properly track preflighted uploads on the server

### LINKED ISSUE #2835: Not displaying max_entries error when multiple uploads
### Environment

* Elixir version (elixir -v): 1.13.1
* Phoenix version (mix deps): 1.7
* Phoenix LiveView version (mix deps): 0.20
* Operating system: Mac 12.7
* Browsers you attempted to reproduce this bug on (the more the merrier): Chrome 
* Does the problem persist after removing "assets/node_modules" and trying again? Yes/no: Yes

### Actual behavior

https://gist.github.com/dankentfield/719666ede4370ab7a9a6c511a82b0983

* Run the script and go to http://localhost:5001/
* Try uploading 3 files (more then the max_entries)
* You will see 2 succeed and land in uploaded and 1 stays in pending, however I expect there to be a max_entries error message for this one.
* If you continue to upload another file it will succeed and add another file to the uploaded files, which now contains more than the max_entries should

### Expected behavior

* Should display the max_entries error when too many files are uploaded (partial success and partial failure).
* It should never upload more than the max_entries.

### LINKED ISSUE #3115: A cancelled LiveView file upload appears to be re-added when adding a new file (or the same file)
### Environment

* Elixir version (elixir -v): 1.14.4 (I also tried with 15.6)
* Phoenix version (mix deps): 1.7.10
* Phoenix LiveView version (mix deps): 0.20.5
* Operating system: OSX
* Browsers you attempted to reproduce this bug on (the more the merrier): Brave, Chrome, Safari
* Does the problem persist after removing "assets/node_modules" and trying again? Yes/no: Yes

### Actual behavior
- Add a file to upload
- Cancel said file
- Add a different file
- Observe that different file is added
- But also observe that the original file is added

I also recorded a video showing the issue if that doesn't make sense!

<details>

https://github.com/phoenixframework/phoenix_live_view/assets/38261603/592fa470-c90e-4cfa-be6b-8ed462352924

</details>

### Expected behavior
- Add a file to upload
- Cancel said file
- Add a different file
- Observe that only the new, different file, is added to be uploaded

### Sample single file app to replicate

```
Application.put_env(:sample, Example.Endpoint,
  http: [ip: {127, 0, 0, 1}, port: 5001],
  server: true,
  live_view: [signing_salt: "aaaaaaaa"],
  secret_key_base: String.duplicate("a", 64),
  pubsub_server: Example.PubSub
)

Mix.install([
  {:plug_cowboy, "~> 2.5"},
  {:jason, "~> 1.0"},
  {:phoenix, "~> 1.7.10", override: true},
  {:phoenix_live_view, github: "phoenixframework/phoenix_live_view", branch: "main"}
])

defmodule Example.ErrorView do
  def render(template, _), do: Phoenix.Controller.status_message_from_template(template)
end

defmodule Example.HomeLive do
  use Phoenix.LiveView, layout: {__MODULE__, :live}

  @impl Phoenix.LiveView
  def mount(_params, _session, socket) do
    {:ok,
     socket
     |> assign(:uploaded_files, [])
     |> allow_upload(:avatar, accept: ~w(.jpg .jpeg), max_entries: 2)}
  end

  def render("live.html", assigns) do
    ~H"""
    <script src={"https://cdn.jsdelivr.net/npm/phoenix@1.7.10/priv/static/phoenix.min.js"}></script>
    <script src={"https://cdn.jsdelivr.net/npm/phoenix_live_view@0.20.5/priv/static/phoenix_live_view.min.js"}></script>
    <script>
      let liveSocket = new window.LiveView.LiveSocket("/live", window.Phoenix.Socket)
      liveSocket.connect()
    </script>
    <style>
      * { font-size: 1.1em; }
    </style>
    <%= @inner_content %>
    """
  end

  @impl Phoenix.LiveView
  def render(assigns) do
    ~H"""
    <form id="upload-form" phx-submit="save" phx-change="validate">
      <.live_file_input upload={@uploads.avatar} />
      <button type="submit">Upload</button>
    </form>

    <section phx-drop-target={@uploads.avatar.ref}>

    <%!-- render each avatar entry --%>
    <%= for entry <- @uploads.avatar.entries do %>
      <article class="upload-entry">
        <figure>
          <.live_img_preview entry={entry} />
          <figcaption><%= entry.client_name %></figcaption>
        </figure>
        <progress value={entry.progress} max="100"> <%= entry.progress %>% </progress>
        <button type="button" phx-click="cancel-upload" phx-value-ref={entry.ref} aria-label="cancel">&times;</button>
        <%= for err <- upload_errors(@uploads.avatar, entry) do %>
          <p class="alert alert-danger"><%= error_to_string(err) %></p>
        <% end %>
      </article>
    <% end %>

    <%= for err <- upload_errors(@uploads.avatar) do %>
      <p class="alert alert-danger"><%= error_to_string(err) %></p>
    <% end %>

    </section>
    """
  end

  @impl Phoenix.LiveView
  def handle_event("validate", _params, socket) do
    {:noreply, socket}
  end

  @impl Phoenix.LiveView
  def handle_event("cancel-upload", %{"ref" => ref}, socket) do
    {:noreply, cancel_upload(socket, :avatar, ref)}
  end

  @impl Phoenix.LiveView
  def handle_event("save", _params, socket) do
    uploaded_files =
      consume_uploaded_entries(socket, :avatar, fn %{path: path}, _entry ->
        # You will need to create `priv/static/uploads` for `File.cp!/2` to work.
        {:ok, path}
      end)

    {:noreply, update(socket, :uploaded_files, &(&1 ++ uploaded_files))}
  end

  defp error_to_string(:too_large), do: "Too large"
  defp error_to_string(:too_many_files), do: "You have selected too many files"
  defp error_to_string(:not_accepted), do: "You have selected an unacceptable file type"
end

defmodule Example.Router do
  use Phoenix.Router
  import Phoenix.LiveView.Router

  pipeline :browser do
    plug(:accepts, ["html"])
  end

  scope "/", Example do
    pipe_through(:browser)

    live("/", HomeLive, :index)
  end
end

defmodule Example.Endpoint do
  use Phoenix.Endpoint, otp_app: :sample
  socket("/live", Phoenix.LiveView.Socket)
  plug(Example.Router)
end

{:ok, _} =
  Supervisor.start_link([Example.Endpoint, {Phoenix.PubSub, name: Example.PubSub}],
    strategy: :one_for_one
  )

Process.sleep(:infinity)
```

### PR DESCRIPTION
**Pull request by SteffenDE**
Fixes #3115.
Relates to #3004.

Please thoroughly review this.

### CODE REVIEW

**Comment by mjrusso** [comment]
Hmm, looks like I'm still seeing phoenixframework/phoenix_live_view#3115. Here's my config, if it's relevant:

```elixir
     socket
     |> allow_upload(:documents,
       accept: ~w(.jpg .jpeg .png .pdf),
       chunk_size: 5 * 1_024 * 1_024,
       chunk_timeout: 30_000,
       max_entries: 20,
       max_file_size: 50 * 1_024 * 1_024,
       auto_upload: false,
       writer: &upload_writer/3
     )
```

If I select a file, then cancel it, then check `socket.assigns.uploads` in an event handler, the entry is still there, and on save it is uploaded.

**Comment by mjrusso** [comment]
@SteffenDE this is what I have in _mix.exs_:

```
{:phoenix_live_view,  github: "SteffenDE/phoenix_live_view", ref: "3331da8b", override: true}
```

_mix.lock_ looks correct, and I did a clean, ensured that _priv/static/assets/app.js_ was rebuilt, etc.

It's possible that I'm still doing something wrong. I'll wipe everything and start with a fresh Docker volume just to be sure.

**Comment by SteffenDE** [comment]
Yes that will still use the old js code, please try `2fccc8c` as ref instead.

**Comment by mjrusso** [comment]
Ah, thank you! I misread `track_preflights_assets` as `track_preflights`. Now I understand what you meant by "built assets" :)

**Comment by mjrusso** [comment]
Thanks @SteffenDE, this branch works great.

To put it through its paces, I've been testing a bunch of scenarios, and I found one that reliably triggers a crash. To reproduce:

- upload two or more files (one of them must be a non-acceptable file type)
- save the form (which fails, because of the non-acceptable file type)
- cancel the upload for the non-acceptable file
- save the form
- GenServer crash with `(ArgumentError) cannot consume uploaded files when entries are still in progress` 

I don't know if this is related to the changes here, but figured it would be good to report in case it's a regression.

**Comment by chrismccord** [comment]
❤️❤️❤️🐥🔥

**Comment by chrismccord** [comment]
@mjrusso your issue was a separate one that already existed and has been fixed on main :) Thanks for the report!

**Pull request merged**
