### PR TITLE
Update CHANGELOG.md

### PR DESCRIPTION
**Pull request by gmile**
Improve markdown by indenting the code blocks under respective list items

### CODE REVIEW

**Comment by SteffenDE** [comment]
This breaks highlighting in ExDoc, but that is probably a bug over there:

image

**Comment by SteffenDE** [comment]
I looked into it, it looks like it's actually a problem in EarMark (https://github.com/RobertDober/earmark_parser/issues/161) - I'll wait for a fix before merging this :)

**Comment by gmile** [comment]
Thanks @SteffenDE!

**Comment by SteffenDE** [comment]
@gmile changing the indentation to match the list item solves it. Committed and added you as co-author. Thank you!

**Pull request closed without merging**
