### PR TITLE
Track feedback within refs on interaction. Closes #3071

### LINKED ISSUE #3071: Some containers do not receive the `phx-no-feedback` class even though they have the `phx-feedback-for` properly defined
### Environment

* Elixir version (elixir -v): 1.14.4
* Phoenix version (mix deps): 1.7.10
* Phoenix LiveView version (mix deps): 0.20.1 `b2c8999aaccf07509bf2f119f7a23d14269bfa26` vs `bed2ff05bb024b2927fb9c1523e42ca55627715f` "Speed up patching 5-10x (#2845)"
* Operating system: Linux Mint
* Browsers you attempted to reproduce this bug on (the more the merrier): Chrome, FF
* Does the problem persist after removing "assets/node_modules" and trying again? Yes/no: Yes

### Actual behavior

Some elements (containers in `phx-feedback-for` parlance) no longer receive the `phx-no-feedback` class when they should i.e. when the `phx-feedback-for` is present with the proper form field name.

I've tried hard to detect the pattern i.e. to find in what way these elements are defined differently than those that still receive the class but so far without success - meaning that at this moment I can't write a demo app replicating this, that is for as long as I can't tell what I am supposed to replicate. 

So far I've tried the following (both isolated and in combo with others) and no combo managed to circumvent the bug :
- removing the element id
- render element unconditionally
- make the element class a static string (as opposed to composed dynamically)
- make the `phx-feedback-for` unconditional static string (as opposed conditioned by the assigns)

I've noticed the bug first when migrated from 0.20.1 to 0.20.3 and then dived into finding the exact commit. If starting from checking out `b2c8999aaccf07509bf2f119f7a23d14269bfa26` which is the last commit without the bug , the bug will not manifest until the "Bump build" in `5a3368da026ea011c2f6790bdd7045ce216402ec` but when going in reverse it will be there in  `bed2ff05bb024b2927fb9c1523e42ca55627715f ` where the relevant changes to `phoenix_live_view.js` were first made.

### Expected behavior

All elements with the `phx-feedback-for` attribute properly set should receive the `phx-no-feedback` class.

### PR DESCRIPTION
**Pull request by chrismccord**

### CODE REVIEW

**Comment by SteffenDE** [comment]
Does not fix
```elixir
Application.put_env(:sample, Example.Endpoint,
  http: [ip: {127, 0, 0, 1}, port: 5001],
  server: true,
  live_view: [signing_salt: "aaaaaaaa"],
  secret_key_base: String.duplicate("a", 64)
)

Mix.install([
  {:plug_cowboy, "~> 2.5"},
  {:jason, "~> 1.0"},
  {:phoenix, "~> 1.7.0"},
  {:phoenix_live_view, github: "phoenixframework/phoenix_live_view", branch: "main", override: true}
])

defmodule Example.ErrorView do
  def render(template, _), do: Phoenix.Controller.status_message_from_template(template)
end

defmodule Example.HomeLive do
  use Phoenix.LiveView, layout: {__MODULE__, :live}

  def mount(_params, _session, socket) do
    {:ok, assign(socket, :count, 0)}
  end

  defp phx_vsn, do: Application.spec(:phoenix, :vsn)
  defp lv_vsn, do: Application.spec(:phoenix_live_view, :vsn)

  def render("live.html", assigns) do
    ~H"""
    <script src={"https://cdn.jsdelivr.net/npm/phoenix@#{phx_vsn()}/priv/static/phoenix.min.js"}></script>
    <script src={"https://cdn.jsdelivr.net/gh/phoenixframework/phoenix_live_view@cm-track-feedback/priv/static/phoenix_live_view.min.js"}></script>
    <%!-- <script src="http://localhost:8000/priv/static/phoenix_live_view.js"></script> --%>
    <script src="https://cdn.tailwindcss.com"></script>
    <script>
      let liveSocket = new window.LiveView.LiveSocket("/live", window.Phoenix.Socket)
      liveSocket.connect()
    </script>
    <style>
      * { font-size: 1.1em; }

      .phx-no-feedback {
        display: none;
      }
    </style>
    <%= @inner_content %>
    """
  end

  def render(assigns) do
    ~H"""
    <%= @count %>
    <button phx-click="inc" class="bg-blue-500 text-white p-4">+</button>
    <button phx-click="dec" class="bg-blue-500 text-white p-4">-</button>

    <.myform />

    <div phx-feedback-for="myfeedback">
      I am visible, because phx-no-feedback is not set!
    </div>
    """
  end

  defp myform(assigns) do
    ~H"""
    <form id="myform" name="test">
      <input type="text" name="myfeedback">
    </form>
    """
  end

  def handle_event("inc", _params, socket) do
    {:noreply, assign(socket, :count, socket.assigns.count + 1)}
  end

  def handle_event("dec", _params, socket) do
    {:noreply, assign(socket, :count, socket.assigns.count - 1)}
  end
end

defmodule Example.Router do
  use Phoenix.Router
  import Phoenix.LiveView.Router

  pipeline :browser do
    plug(:accepts, ["html"])
  end

  scope "/", Example do
    pipe_through(:browser)

    live("/", HomeLive, :index)
  end
end

defmodule Example.Endpoint do
  use Phoenix.Endpoint, otp_app: :sample
  socket("/live", Phoenix.LiveView.Socket)
  plug(Example.Router)
end

{:ok, _} = Supervisor.start_link([Example.Endpoint], strategy: :one_for_one)
Process.sleep(:infinity)
```

**Comment by chrismccord** [comment]
that form is entirely stateless, (fully client side), so I wouldn't expect it to work as the server never touches the input

**Comment by SteffenDE** [comment]
Hmm well.. Something like this did work before the magicId optimization :(

**Comment by chrismccord** [comment]
This example seems contrived because in what cases would you have a purely client side input tracking feedback, which is used for showing feedback that the server renders for that input? Maybe I'm missing a usecase?

**Pull request closed without merging**
