### PR TITLE
Recreation of bug with statics not resolving correctly across recursive diffs

### PR DESCRIPTION
**Pull request by sb8244**
Diffs came from the view at https://github.com/sb8244/dynamic-query-example/commit/1a1a9891dfdb5d254d883d6fd07d333b1f32faf3 You can check out that code to reproduce the problem in the wild.

This is a draft PR because I don't have the bug fixed. I wanted to share it and open it up for discussion if necessary. Feel free to close if it's added noise and there's a better solution for discussion.

I've attached a clip of the issue occurring.

https://user-images.githubusercontent.com/1231659/125981887-92587d4a-a892-4687-82d8-0a0cedc556ca.mov

### CODE REVIEW

**Comment by sb8244** [comment]
For reference, this is the issue that I was seeing in https://github.com/phoenixframework/phoenix_live_view/issues/1144#issuecomment-880069118. I believe it's unrelated to that code, just the same error manifesting differently.

**Comment by josevalim** [comment]
This seems to be a bug on the server. We don't send the statics if the comprehension is empty but then it seems we are not sending them when the comprehension finally gets a value.

**Comment by josevalim** [comment]
Can you please try removing this clause and let us know if the issue is fixed in the app? https://github.com/phoenixframework/phoenix_live_view/blob/master/lib/phoenix_live_view/diff.ex#L411-L414

**Comment by josevalim** [comment]
I have a proper fix. It is a bug on Elixir front. I was struggling to reproduce it because it only happens when the change is triggered via a component event (and not the root).

**Pull request closed without merging**
