### PR TITLE
Updating to the latest version number

### PR DESCRIPTION
**Pull request by gushonorato**

### CODE REVIEW

**Comment by chrismccord** [comment]
❤️❤️❤️🐥🔥

**Comment by Grantimus9** [comment]
Thanks @gushonorato, this fixes a "live_component not defined" compile error for those following these installation instructions.

**Comment by gushonorato** [comment]
@Grantimus9 it's me who should have to thanks those who make available this great piece of technology :)

By the way, I read the docs but it's still not clear to me what's the difference between Live View and Live Component. When should I use one or the other?

**Comment by preciz** [comment]
@gushonorato 

When your LiveView gets big you start to use functions to store different chunks of HTML and you get a huge module with many event handlers.

So I think the core team saw this and improved the structure with introducing LiveComponent
which helps separate events, markup, state without spawning a new process + other benefits.

If you haven't run into this or any problem just use LiveView.

**Pull request merged**
