### PR TITLE
clarify stream bulk insert (#3023)

### PR DESCRIPTION
**Pull request by SteffenDE**
References #3023

### CODE REVIEW

**Comment by LostKobrakai** [comment]
This feels like something that should be handled by LV. When bulk inserting a list I'd expect the index to be the index at which the list is slotted in, not the index at which items will be inserted at one by one. The user here shouldn't need to care about how this is implemented internally.

**Comment by SteffenDE** [comment]
This is not ready to merge yet. We'll have to fix LiveViewTest because reversing does not help there.

**Comment by SteffenDE** [comment]
I added a test that currently fails because of the LiveViewTest issue.

**Comment by chrismccord** [comment]
❤️❤️❤️🐥🔥

**Pull request merged**
