### PR TITLE
Bump version

### PR DESCRIPTION
**Pull request by seb3s**

### CODE REVIEW

**Comment by josevalim** [comment]
~> always gets the latest on v0.13, so we don't need to always update it, but we should update it when 0.14 and so on comes out. :)

**Comment by seb3s** [comment]
Ok, why not 0.13.0 in that case ?

**Comment by seb3s** [comment]
I find it a bit misleading coz I have  {:phoenix_live_view, "~> 0.13.2"} in my file.
When i run "mix deps.get", it is not upgraded as the dependencies version is satisfied.
I have to run "mix deps.update phoenix_live_view" to get the latest.
But the above documentation in installation introduce "mix deps.get" to get the latest. Hence why I prefer to get the latest here as well ;-)

**Comment by josevalim** [comment]
Yes, upgrades are always explicit. But for installation, which is the purpose, the current one is enough! Thanks!

**Pull request closed without merging**
