### PR TITLE
Start LiveViewTest.UploadClient Supervised

### PR DESCRIPTION
**Pull request by mveytsman**
This is my attempt at fixing: https://github.com/phoenixframework/phoenix_live_view/issues/1269

The issue is that the UploadClient will exit under normal operation, but it's started linked to the test process and kills the test.

In this PR I'm starting it supervised the way we do the client proxy.

I've also removed the `trap_exit`s from the the test as these are no longer needed -- we're monitoring the pids we need and they aren't linked to the test.

There's still one more place where we have a trap exit that I'm not sure about in the tests...

### CODE REVIEW

**Comment by mveytsman** [comment]
I am not sure but I think the failing test might be flaky. The file gets deleted when the `UploadChannel` exits, monitored by `Plug.Upload`. 

I think if we also monitor `channel_pid` in this test and wait for it to exit that should fix the flakiness -- I can add that to this PR if it's helpful but I haven't been able to reproduce the flaky test on my end :(

**Comment by josevalim** [comment]
> I think the failing test might be flaky. The file gets deleted when the UploadChannel exits, monitored by Plug.Upload.

Is the test accessing the file after consuming it? Then yes, that won't be deterministic.

When consuming, you can monitor the channel and then wait for it to be down afterwards. That should make the failure more consistent (but still not guarenteed and the Plug.Upload still has to remove it). Another trick you can use is this:

    elixir --erl "+T 9" -S mix test

This runs the VM with different timings on the schedulers, helpful to catch heisenbugs!

**Comment by josevalim** [comment]
Btw, this PR looks great!

**Comment by mveytsman** [comment]
> Btw, this PR looks great!
:smile: I fixed the nondeterminism!

**Comment by josevalim** [comment]
:green_heart: :blue_heart: :purple_heart: :yellow_heart: :heart:

**Pull request merged**
