### PR TITLE
Repurpose phx-target for client event scoping

### PR DESCRIPTION
**Pull request by chrismccord**

### CODE REVIEW

**Comment by msaraiva** [comment]
Hi Chris!

First, thanks again for LiveView and its new component API. I'm very excited to be able to build **Surface** on top of it. It's just awesome!  

I started to test the new `phx-target`. It works just fine as expected. However, I find its behaviour quite unorthodox. Here's why:

  1. I believe users will expect that events would, BY DEFAULT, be handled locally and not by the parent live view. After all the whole point is to promote the use of isolated components, right? So it might sound kind of weird that, by default, the event is handled by a possibly distant parent liveview up in the tree.

  1. As far as I could see, `phx-target` is applied globally across all events in a component, so if the user decides to handle one event in a target, he'll be forced to handle all other events in that same target too. I think that could lead to confusion, especially if the user is adding behaviour to an existing component that already handles other events.

I'm sure there are good reasons behind those design choices so I have just one question.

Is it possible/planned to have `phx-target` per event? Something like `phx-target-click`, `phx-target-keydown` and so on? This way I could at least add some syntactic sugar around events, improving dev experience by not forcing the user to pass the target to every single component down the tree.

Cheers.

**Comment by chrismccord** [comment]
> 2\. As far as I could see, `phx-target` is applied globally across all events in a component

the target is only per binding, ie this works just fine:

```elixir
# my_component.ex
<div id="my-component">
  <button phx-click="click" phx-target="#mycomponent">me</button>
  <button phx-click="click" phx-target="#target2">other</button>
</div>
```

**Comment by josevalim** [comment]
@msaraiva unfortunately we cannot implement 1 exactly because when you call a component and you pass markup to it, it is impossible to know what is the parent and what is the child. This is how we wanted it to behave before but it is not possible to implement it.

**Comment by msaraiva** [comment]
I guess I wasn't clear enough. My bad. What I meant with "all events in a component" is that:

Suppose I have a component that handles focus/blur locally:

```
<div id="my-component">
  <button phx-focus="focus" phx-blur="blur" phx-target="#mycomponent">me</button>
</div>
```
and now, for some reason I want to handle the `phx-click` event in the parent. How can I achieve that?

```
<div id="my-component">
  <button phx-focus="focus" phx-blur="blur" phx-click="parent_handler" phx-target="#mycomponent">me</button>
</div>
```

**Comment by josevalim** [comment]
Ah, totally. We can always add new APIs in the future, such as phx-click-target.

**Comment by msaraiva** [comment]
> This is how we wanted it to behave before but it is not possible to implement it.

@josevalim I understand perfectly there reasons behind the design choice. That's why I'm curious about `phx-*-target`. If we had that, I could this "solve" this problem and provide the behaviour that was originally desired. Remember that Surface knows who the parents and children are.

**Comment by josevalim** [comment]
Remember the original problem applies to both LiveVew and Surface, so even if Surface can track it, we need a solution that does not burden users not using Surface. We can add phx-*-target if that is the ideal solution for Surface, but it does not preclude this patch. :)

**Comment by chrismccord** [comment]
> and now, for some reason I want to handle the `phx-click` event in the parent. How can I achieve that?

I don't think the overlap is too severe to handle the proxy yourself in such cases. For example we still have `send` and `send_update` on the server side to enable these scenarios, but I'm not sure how often in practice you'll have different targets per element?

**Comment by msaraiva** [comment]
> Remember the original problem applies to both LiveVew and Surface, so even if Surface can track it, we need a solution that does not burden users not using Surface

Exactly! That's why `phx-*-target` sounds reasonable. It has nothing to do with Surface directly. Surface will just use it to solve another very diferrent problem.    

> I don't think the overlap is too severe to handle the proxy yourself in such cases. For example we still have send and send_update on the server side to enable these scenarios, but I'm not sure how often in practice you'll have different targets per element?

The thing is when you start using an approach based on components (no matter if using Surface, LV or even React and friends) you end up with lots of separated isolated components. The more you split your view into smaller components, the more you'll need to handle different events of the same child in different layers of the hierarchy. The natural way to do this is to start passing some of those events as parameters/properties. However, in order for this to work properly, the child component (which should work as a black box) should NOT make any assumption about where the event will be handled. Otherwise, it breaks the model and passing events will become problematic since the parent can no longer define who will handle the event.

**Comment by msaraiva** [comment]
And just for completeness, I the root of the problem lies on the fact that in LV an "event" is just a string that represents the "what", not the "where". Conceptually, in any other component-based framework, an event is a reference to a method/function so it implicitly holds both, the "what" (method) and the "where" (class). Adding the `phx-*-target` is just a way to improve the model by making it possible to provide the "where" part.

**Comment by josevalim** [comment]
> Exactly! That's why phx-*-target sounds reasonable. It has nothing to do with Surface directly. Surface will just use it to solve another very diferrent problem.

We are agreeing then. :) It somehow sounded like you wanted us to get rid of phx-target, but it seems we are all agreeing on having *both*.

**Comment by josevalim** [comment]
@msaraiva please open up an issue on supporting "phx-*-target". :)

**Comment by msaraiva** [comment]
> We are agreeing then. :) It somehow sounded like you wanted us to get rid of phx-target, but it seems we are all agreeing on having both.

Sure. I don't want to get rid of `phx-target` at all. Sorry for not being clear about that since the beginning. Calling the solution "unorthodox" certainly gave that impression :)

What I meant was that the behaviour is quite different from what we usually find in other solutions, which, btw, is totally fine for LV since it's already different in many ways. I just wanted to give you guys some feedback about using it with Surface which takes a more "standard" way when it comes to components.

I'll open an issue for it. Thanks a lot, guys!

**Pull request merged**
