### PR TITLE
Add support to temporary_assigns with atoms

### LINKED ISSUE #794: Allow temporary assigns to have "magic" default value
We want to allow temporary assigns to be defined like this:

    temporary_assigns: [:one, :two, three: []]

For :one and :two, it will be equivalent to setting it to `%Phoenix.LiveView.UnsetTemporary{}`, which will raise a meaningful error whenever picked up by `Phoenix.LiveView.EEx.fetch_assign/2`.

### PR DESCRIPTION
**Pull request by caironoleto**
Closes #794

### CODE REVIEW

**Comment by josevalim** [comment]
Hi @caironoleto! This looks great. You should also [change this function](https://github.com/phoenixframework/phoenix_live_view/blob/master/lib/phoenix_live_view/engine.ex#L854) to raise if UnsetTemporary is given.

**Comment by caironoleto** [comment]
@josevalim I didn't find a way to use atom in the mount of the temporary assigns and throw the exception in `fetch_assign` since the page is rendered by calling `fetch_assign` **after** the mount. In the end, I had to set the temporary assigns as a keyword list.

With these changes, all tests passed but failed with my app.

```diff
# lib/phoenix_live_view/engine.ex

   def fetch_assign!(assigns, key) do
     case assigns do
+      %{^key => %UnsetTemporary{}} ->
+        raise ArgumentError, """
+        @#{key} is assigned with %Phoenix.LiveView.UnsetTemporary{}.
+
+        Please make sure all proper assigns have been set.
+        """
+
       %{^key => val} ->
         val
```
```diff
# test/phoenix_live_view/engine_test.exs

+    test "raises ArgumentError for UnsetTemporary assigns" do
+      assert_raise ArgumentError,
+                   ~r/@bar is assigned with %Phoenix.LiveView.UnsetTemporary{}./s,
+                   fn -> render("<%= @bar %>", %{bar: %UnsetTemporary{}}) end
+    end
```

**Comment by josevalim** [comment]
Those changes look good to me. How do they fail in your app?

**Comment by caironoleto** [comment]
In the end, with these changes, I can't set a temporary assign with atoms, because will raise an error in `fetch_assign`. X)

**Comment by josevalim** [comment]
@caironoleto but that's the goal. They should raise if you try to use them and they are unset! :D Does that make sense? Or do you mean you can *never* use them?

**Comment by caironoleto** [comment]
With this approach, we'll never set temporary assigns with just an atom, because always will raise the error. We'll never achieve `Add support to temporary_assigns with atoms`.

**Comment by josevalim** [comment]
Even if you explicitly assign them later on? Even if later you do assign(socket, :some_temporary_assign, value)?

**Comment by caironoleto** [comment]
I will try! :D

**Comment by josevalim** [comment]
Ping! :)

**Pull request closed without merging**
