### PR TITLE
Allow multiple hooks in phx-hook tags, separated by space

### PR DESCRIPTION
**Pull request by mreishus**
`<div phx-hook="Draggable Colorable"></div>` Will apply both the `Draggable` and `Colorable` hooks to that div.

The usual case of having only one hook still works exactly the same.  Added a test case showing that the case of two hooks gets those two applied in order.

### CODE REVIEW

**Comment by snewcomer** [comment]
@mreishus I like what you did!  I wanted to offer another approach though that is also easily accomplished via function composition in case we find the implementation not maintainable or not desired as a part of the longer term plans.

`<div phx-hook="DragAndColor"></div>`

```js
Hooks.DragAndColor() {
  mounted() {
    draggable();
    colorable();
  }
}

function draggable() {
}
function colorable() {
}
```

Based on your needs, do you see how this perhaps doesn't handle your needs?  Thanks again 👍

**Comment by mreishus** [comment]
I implemented something like that in my own project, but it was a little more complicated since I also needed to be able to apply individual hooks.  See here:

- [draggable.js](https://github.com/mreishus/demon_spirit_umbrella/blob/master/apps/demon_spirit_web/assets/js/hooks/draggable.js)
- [droppable.js](https://github.com/mreishus/demon_spirit_umbrella/blob/master/apps/demon_spirit_web/assets/js/hooks/droppable.js)
- [draggable_droppable.js](https://github.com/mreishus/demon_spirit_umbrella/blob/master/apps/demon_spirit_web/assets/js/hooks/draggable_droppable.js)

It worked, but I could see the amount of work quickly ballooning if either of the hooks implemented more than just a `mounted()`, or if you had say, 5+ hooks and needed different combinations of them.

**Comment by snewcomer** [comment]
I think your function composition solution looks pretty concise and elegant! Even with 10 hooks, something like what you implemented in your codebase looks good and really helps describe what is happening to your teammates (could also use pure functions without the `apply`).  Also, users could theoretically use the result from the first and pipe it into the second if they managed that themselves.  Defining multiple hooks and live_view handling it makes that much harder.

There is always a decision of what a library should handle and the client should handle.  Where libraries end up backing things out is often when those lines are blurred.  I would personally advocate for users handling this logic since your client side code looks elegant, but I'll leave the final decision to others!

**Comment by mreishus** [comment]
I see `phx-hook="hook1 hook2"` as meaning *if any hookable event occurs, call it on hook1, then call it on hook2* to be a natural, unsurprising definition of composing hooks.  It would not prevent writing a custom composition of hooks using a method similar to the one above.  The user could simply not use the provided hook composition and write their own helper.

The reason I was worried about having 5, or 10 hooks is how many different ways there are to pick 2 hooks from a larger set.  10 choose 2 is 45, and 10 permute 2 is 90.  Obviously all of those won't exist, but it would seem like a waste to have to write a bunch of helper files that all boil down to "Run hook1, then run hook2."  It makes me think of css requiring me to write a helper for *class="large green indent"* because those classes have never been combined before.

I'm not particularly attached to my implementation; I'm not used to the code style of `phoenix_live_view.js`, so I can see how my diff would clash with it.  I just hoped to bring more to the table than a feature request.

That said, I've only made one small liveview app, so I'm not sure of the community demand for it.

**Comment by chrismccord** [comment]
I have considered a `mixin` or similar attribute on hooks that would allow you to compose them. I would prefer this to bundling hooks inside the markup. In the meantime, Scott's suggestion is a good starting point. Note, that you anyone could implement your own `mixing` style today using hooks as a building block. I will revisit providing something like this on our end once I round out some other work, but the concern for us is not going too far beyond the JS escape hatch for user-land to implement their own features. Stay tuned. Thanks!

**Pull request closed without merging**
