### PR TITLE
capture and restore the innerHTML of a disabled element, not just the text

### PR DESCRIPTION
**Pull request by iwarshak**
I ran into an issue where a failed form submission did not restore the button to the proper state. The button is using some font-awesome web icons, and looks like this:

```
<%= submit id: "save-btn", "phx-disable-with": "Saving..." do %>
  Next <i id="next-btn" class="fas fa-angle-double-right"></i>
<% end %>
```

It would get restored to a button with the text of: "Next", but completely lose the font awesome icons. 

This PR captures the innerHTML of the element to be restored, not just the text.

### CODE REVIEW

**Comment by chrismccord** [comment]
phx-disable-with only supports textual content. There are technical limitation reasons we decided to only support textual vs HTML as this PR outlines, but I forget the nuances at the moment. The best option today for this kind of behavior is to use the phx-submit-loading css classes to swap two different containers of the form. Thanks!

**Comment by iwarshak** [comment]
@chrismccord this PR is not to support anything complex in the phx-disable-with, but rather it's to actually properly save and restore what it is replaced. 

If a button contains anything other than text, then after it gets restored it will lose those elements.

**Comment by chrismccord** [comment]
> If a button contains anything other than text, then after it gets restored it will lose those elements.

Right – we can only swap the `innerText`, and there are blocking issues with swapping HTML, but I forget the particulars at the moment without looking back into it. We document the limitations in the form-bindings docs

**Comment by iwarshak** [comment]
👍  - understood, thanks!

**Pull request closed without merging**
