### PR TITLE
List component systems on README

### PR DESCRIPTION
**Pull request by josevalim**
A component system is often on the top of the list of required LiveView features, so let's list them in the README.

We can add new systems as well. If any system is no longer developer, we can remove it. I probably want to duplicate this list in Phoenix docs later on.

/cc @chrisgreg @woylie @nhobes @ArthurClemens @mitkins @bluzky

### CODE REVIEW

**Comment by Fudoshiki** [comment]
@josevalim Hello, I made an https://github.com/Youimmi/phoenix_asset_pipeline, but is it possible to integrate it into Phoenix, like sprockets rails?

**Comment by chrisgreg** [comment]
Planning some big additions to Bloom soon so very much active 👍🏼

**Comment by josevalim** [comment]
:green_heart: :blue_heart: :purple_heart: :yellow_heart: :heart:

**Comment by josevalim** [comment]
Hi @Fudoshiki, thanks for reaching out. At the moment we are listing only the component systems themselves, as those are commonly asked by the community.

**Comment by ArthurClemens** [comment]
Thanks for listing my project.
I just now noticed that "An implementation of GitHub's Primer Design System using Phoenix LiveView -" contains a trailing dash.

**Comment by Fudoshiki** [comment]
@josevalim, thanks for answer, I don't mean to list my package, I mean the general idea for phoenixframework about a general package for assets

**Comment by SteffenDE** [comment]
@Fudoshiki please don’t use issues to discuss unrelated topics. You can use the proposals section in the Elixir forum instead (https://elixirforum.com/c/phoenix-forum/proposals-suggestions/126). I‘d say though that this is out of scope for Phoenix itself. Going with a separate package, as you do now, is the way to go im my opinion :)

**Comment by nhobes** [comment]
@josevalim thanks for including us ❤️

**Pull request merged**
