### PR TITLE
Extended phx-target API to accept phx-event-target

### LINKED ISSUE #554: Extend phx-target API to accept phx-event-target
Allow the parent component to override the target for an individual event using `phx-event-taget`. The original discussion can be found here: https://github.com/phoenixframework/phoenix_live_view/pull/551

### PR DESCRIPTION
**Pull request by haseebeqx**
fix #554

### CODE REVIEW

**Comment by chrismccord** [comment]
I'm not sure whether or not this change is worth it. Can you give a usecase where this would solve an issue you have? Thanks!

**Comment by haseebeqx** [comment]
As per @msaraiva , This is the main reason https://github.com/phoenixframework/phoenix_live_view/pull/551#issuecomment-572084694

If there are multiple event listeners in a component and we want the component to handle click event only.

with current `phx-target` it will be difficult.
```html
<div id="my-component">
  <button phx-focus="focus" phx-blur="blur" phx-click="click" phx-target="#mycomponent">me</button>
</div>
```
and with event specific target it is possible.

```html
<div id="my-component">
  <button phx-focus="focus" phx-blur="blur" phx-click="click" phx-click-target="#mycomponent">me</button>
</div>
```

**Comment by josevalim** [comment]
Thanks @haseebeqx, we understand that's the use case. :) The question is: what is the scenario you have at the moment where the same element/markup needs to have events pointing to different components?

**Comment by haseebeqx** [comment]
For example in a resusable password field. We can add password validations on keydown. Or as in my case a reusable search field with autocomplete.

**Comment by haseebeqx** [comment]
This is my example requirement, There will be multiple delivery outlets in an area. Place and zip are two searchable fields. on keydown they show autocomplete results and on change they will fetch top 10 matching outlets in the area. Here, on change will be handled in parent and keydown on child.

**Comment by msaraiva** [comment]
Hi @chrismccord!

> I'm not sure whether or not this change is worth it. Can you give a usecase where this would solve an issue you have?

I'm not sure if it's relevant, but this is extremely worth it for **Surface** since we're trying to bring the model closer to the current mainstream "natural" way of handling events. 

The problem is conceptual in my opinion. In general, a component is a generic abstraction that's supposed to be **reusable**. In order to be reusable, it's imperative that it makes as fewer assumptions as possible. Assuming that **ALL** events of an HTML element will be handled by a single component limits the reusability a lot because it makes passing events as properties (assigns) completely **unpredictable** (from the user PoV) and sometimes even **impossible**. 

If, for whatever reason, a button already handles an event internally to implement a **generic feature**, let's say, to change the way it looks on `focus/blur`, that means it can no longer expose a `click` event to the parent because the `phx-target` is already set. We have lost the power of reusability and we're not able to implement a simple button just because we assumed that the event `focus` is somehow related to the `click` event, but the fact is: they may not be related at all! One has to be implemented locally because it's generic, the other has to be exposed so the user can inject the custom behaviour.

The same concept is also valid for `keydown` events. I might need to use arrow keys to move a component around (I'm not telling it's a good idea) but let the parent decide what to do when I `click` on it. 

The truth is that we don't know which events should be handled by which component until we identify what should be **generic (local)** and what's **customizable (exposed)**. To make it worse, once you identify the customizable part and you expose any event, the component automatically loses the power of defining who's responsible for handling the event, only the parent (the one that holds the handler) knows that. 

It's clear to me that this solves a real problem in the current model. What's it's not clear to me are the downsides of the proposed solution. I'd love to hear about them so I can understand the reasons to keep this limitation.

Cheers.

**Comment by msaraiva** [comment]
Just to make it clear. I totally agree that you guys should be very careful when adding new features. Discussing the pros and cons is essential, that's what I'm here for ;)

I just hope I was able to present some of the **pros** and I'd sincerely love to hear some of the **cons** so we can maybe find a better solution, if possible.

**Comment by haseebeqx** [comment]
I agree with @msaraiva 

@chrismccord Feel free to close this PR if this is not worth it. Next time, I will make sure to ask for details for before creating PRs.

cheers.

**Comment by haseebeqx** [comment]
What is the status of this?. 
Can we close this if it is not needed?. 
I am sorry, It is affecting a decision I have to make.

**Comment by josevalim** [comment]
Per the discussion above we are not quite confident this is the way to go, so it is better if you consider this won't be available when making your decision.

**Comment by haseebeqx** [comment]
@josevalim Thank you!

**Comment by msaraiva** [comment]
Hey @haseebeqx!

> ... It is affecting a decision I have to make.

As far as I could see, this PR hasn't been merged yet because we need to provide a "real" use-case for it. So it looks you DO have a real use-case. Could you share how the lack of this feature affects your decision? I mean, how did you solve the problem without this feature?

**Comment by chrismccord** [comment]
Things are lagging mainly because I have been busy on other features and I need to give this one some serious consideration along with other alternatives before I would move forward, so bear with us :)

**Comment by msaraiva** [comment]
Hi @chrismccord!

No worries! I'm sure you have other priorities. I'm just curious about how @haseebeqx worked around this issue. Maybe it could help us to find an alternative ;)

Cheers.

**Comment by haseebeqx** [comment]
@msaraiva
Lets say if I want to make this https://github.com/chrismccord/phoenix_live_view_example/blob/master/lib/demo_web/live/search_live.ex search field reusable. 

Suggestions will be handled in this component and results will be fetched and shown in wherever it is used. 
but it can be solved by using http requests. The decision I had to make was based on whether I should use a frontend library or not.

**Comment by ccapndave** [comment]
I don't have a real use case for `phx-event-target`, but I have one for `phx-event-debounce`.  I know this isn't quite the same issue, but its very similar so I've put it here.  If you want me to open this as a new issue instead let me know.

In one of my applications there is a set of inputs that can be edited by multiple users at once on different clients.  The way that the concurrency is managed is that if one user focuses an input, all other users have the input disabled with an _another user is editing this_ graphic on it.  When the input is blurred, other users get their input re-enabled.

I want to send this event ASAP to other clients, and therefore I want `phx-focus` to happen instantly.  However, I don't want `phx-change` events to fire every time they press a key; instead I want to debounce it by 1000ms or similar.

Therefore I want:
```
<form phx-change="change">
  <input phx-focus="lock" phx-blur-"unlock" phx-focus-debounce="0" phx-blur-debounce="0" phx-change-debounce="1000" />
</form>
```

(or similar).

**Comment by henrik** [comment]
Might be nice with a per-callback debounce, even, rather than a per-type one. 

I have a settings form with no submit button where both the name and email field automatically persist their values on change. Here a debounce of 500 ms or so would be nice.

But one of the fields also shows a live preview of what you have entered. Something like saying “Hi, <%= @name %>” which looks better with a much lower debounce.

So for this use case, something to the effect of `phx-change=“persist:debounce-500, preview:debounce-100”` could be handy. That’s not a well-considered syntax suggestion, just the first thing that popped into my head.

Such a feature could also be used for per-event-type denouncing as suggested by @ccapndave.

**Comment by henrik** [comment]
Hope I'm not derailing this issue, but I figured I might as well add on another thought about the callback syntax, since I guess the bigger situation here is thinking about where to go with it in a wider sense.

Having started using components more, something like `phx-click="complete->#my_id"` could be nice as a more light-weight alternative to `phx-click="complete" phx-target="#my_id"`. One of the reasons I was reluctant to use components more was that adding multiple attributes like this feels a little laborious.

Merged with my previous suggestion it could look something like `phx-change="persist:debounce-500->#my_id, .my-class; preview:debounce-100"`.

**Comment by tmjoen** [comment]
My usecase more or less matches @njouanin's. I have extracted a lot of boilerplate form validation logic into its own component, but I'd still like to send the submit event to the LiveView, since the handling of that event will vary from view to view.

**Pull request closed without merging**
