### PR TITLE
re-enable production source maps

### PR DESCRIPTION
**Pull request by maennchen**
* introduced in #1385
* removed again in #1474
* mailing list https://groups.google.com/g/phoenix-core/c/Dk2AbXVnzeg
* `phoenix` counter-part https://github.com/phoenixframework/phoenix/pull/4276

### CODE REVIEW

**Comment by maennchen** [comment]
Amended compiled JS & Source Maps as discussed with @bcardarella

**Comment by bcardarella** [comment]
@chrismccord :+1: from me on this, should be OK to merge

**Comment by chrismccord** [comment]
@maennchen thank you! Can you back out the precompiled changes and I will rebuild after merging? We prefer to avoid precompiled builds in PRs for conflicts and security reasons. Thanks!

**Comment by bcardarella** [comment]
@chrismccord the pre-compile is necessary to reference the sourcemap file, otherwise the js console won't know how to associate the two

**Comment by chrismccord** [comment]
to be clear, I will build the the source/maps after I merge and everything else is perfect, we just prefer to avoid merging minified/compiled js since it can be an easy security backdoor as it is not human readable.

**Comment by bcardarella** [comment]
@chrismccord ah ok, makes sense :+1:

**Comment by maennchen** [comment]
@chrismccord / @bcardarella The dist files are now removed.

**Comment by maennchen** [comment]
@chrismccord / @bcardarella Is there any change needed on this PR?

**Comment by bcardarella** [comment]
Should be OK to merge

**Comment by chrismccord** [comment]
❤️❤️❤️🐥🔥

**Pull request merged**
