### PR TITLE
Change to Event Targeting Behaviour

### PR DESCRIPTION
**Pull request by wrren**
This change reflects the behaviour described in the Elixir Forum thread [LiveView Event Targeting in 0.5x](https://elixirforum.com/t/liveview-event-targeting-in-0-5x/28354). Basically, the current event targeting behaviour specifies that events will, by default, be handled by the LiveView that rendered the DOM element that emitted the event. 

This presents difficulties when writing stateful components (i.e, a component that implements `handle_event/3`), as it's necessary to ensure that every event is targeted using the `phx-target` attribute. It's also necessary to set a DOM ID for a parent element within the markup rendered by the component, which then acts as the `phx-target` value. This is complicated further when rendering non-unique components, such as a list item, as the DOM ID used must then also be unique, and so there's a burden on the developer to generate and specify a unique DOM ID per-component, and ensure that all events are correctly targeted using `phx-target` attributes.

This PR changes this behaviour in the following ways:

- Emitted events are, by default, bubbled up to the nearest stateful component or live view.
- Stateful components receive the `data-phx-stateful` attribute, which makes them eligible to receive events.
- Events can be targeted at the parent live view explicitly by using the `phx-target-parent` attribute, no value is required.

I believe this approach reduces the cognitive load on developers, and the likelihood for error, the hypothesis being that developers would expect events emitted from inside their stateful components to be routed to that component automatically, and routing them to the parent live view actually represents an unusual requirement that should not be the default.

I realise that this may not represent the desired behaviour of the maintainers, but I'd be interested in starting a discussion. As an avid user of LiveView, this change represents a behaviour that would greatly simplify my use case, which is what's provoked this PR.

### CODE REVIEW

**Comment by josevalim** [comment]
Hi @wrren, thanks for the PR!

Unfortunately I don't have anything new to add beyond our discussion on ElixirForum. As mentioned in the forum, the syntax that you propose is ambiguous and it can also happen with stateful components. For example, someone could implement a presence component that I would use like this:

```html
<%= live_component Presence, topic: "users" do %>
  <%= for user <- @users do %>
    <span phx-click="show-user-info" phx-value="<%= user.id %>"><%= user.name %></span>
  <% end %>
<% end %>
```

As you know, if your patch is accepted, the phx-click event will now go to the component unless we explicitly say it goes to the parent. Your PR does provide phx-target-parent but the parent is not a sufficient solution because maybe the Presence topic delegates to another component, providing its own events on top of the user supplies ones, and now you have different levels of nesting. It is impossible for you to know upfront the nesting a given do/end block will be used at.

We understand the current approach is verbose but it is the only solution that avoids ambiguity *all the way*. Changing the defaults means that things will work sometimes and sometimes they won't, and sometimes they never will.

Maybe there are better solutions for this problem, but we are certain that changing the default to what it previously was is not the path we want to go.

**Comment by wrren** [comment]
I think there's a misunderstanding about `phx-target-parent`, probably due to my poor naming; that attribute will cause the event to be sent to the live view, not to a parent stateful component. So basically it's a way to signal that you want to use the current default behaviour, i.e all events go to the live view for handling. So in this way there's no additional complication from nesting of stateful components; they're all bypassed in favour of the live view when using `phx-target-parent`.

I feel that the current approach is optimizing for a less popular use-case (although I have no data for this apart from my own projects). Are you encountering widespread use of do-block components? If we assume that the most common use of components is self-contained markup, then forcing the use of `phx-target` is a headache for most users.

**Comment by josevalim** [comment]
> I think there's a misunderstanding about phx-target-parent, probably due to my poor naming; that attribute will cause the event to be sent to the live view, not to a parent stateful component. 

This interpretation does not solve the problem. A component may want to pass its own EEx block to other components and they need to target the parent component too.

> I feel that the current approach is optimizing for a less popular use-case (although I have no data for this apart from my own projects).

While this may as well be the case, it is not the point of the discussion. At least the current solution works on all scenarios. It is not an option to revert back to a solution that 1. is a confusing default in some cases and 2. does not work at all in other cases.

Maybe there is another solution that solves all of these problems out there and we will be glad to adopt it once we find it.

**Comment by wrren** [comment]
To be clear: the PR still retains `phx-target`, it just changes the behaviour when that attribute isn't present. So in a situation where there are events emitted from markup that should be handled by a component higher up in the DOM, that's still possible.

**Comment by josevalim** [comment]
Alright, that solves the component to component case. The issue is the rules to make events work now are:

1. If you are in a LiveView, you don't need to do anything UNLESS you are passing do/end to a component. Then you need to use phx-target-parent.

2. If you are in a component, you don't need to do anything UNLESS you are passing do/end to a component. Then you need use something else, which is phx-target.

While today the rule is simply "if you are in a component, use phx-target". My biggest concern is that once people start providing some out-of-the-box components for others to use, rule 1 will really bite people, because as they refactor stuff and move code around, they need to add phx-target-parent attributes to their components.

I believe have already mentioned this though. :) So I still don't believe this is an improvement to the current behaviour. I guess we will have to agree to disagree. Thanks!

**Comment by wrren** [comment]
Indeed! I appreciate you taking the time to discuss this with me. As an avid user of the library, I would like to ask that the API around this be given another look, as I am finding it more painful to use than it was before the introduction of `phx-target`. I might suggest that a reasonable compromise would be the addition of a `phx-target-component` attribute, or something along those lines, that targets the component that rendered the markup. The reason this would be easier, for me at least, is that currently I need to:

1. On component `update`, retain the `:id` passed to my stateful components so I can use it to set the DOM ID of a wrapping HTML element.
2. Set a DOM ID matching that ID on some wrapping element.
3. Remember to set `phx-target` on all elements that emit the event, otherwise they go to the Live View.

So something that would let me just ignore the component ID from within the component would be helpful.

**Pull request closed without merging**
