### PR TITLE
Add data and aria to globals

### LINKED ISSUE #2217: warning: undefined attribute "data" (declarations)
### Environment

* Elixir version (elixir -v):

Erlang/OTP 25 [erts-13.0.4] [source] [64-bit] [smp:10:10] [ds:10:10:10] [async-threads:1] [jit] [dtrace]

Elixir 1.14.0 (compiled with Erlang/OTP 25)

* Phoenix version (mix deps):

phoenix 1.6.12 (Hex package) (mix)

* Phoenix LiveView version (mix deps):

phoenix_live_view 0.18.0 (https://github.com/phoenixframework/phoenix_live_view.git - a3715873f22fb0e0b0ff9cb81d79567f7dd3f433) (mix)

* Operating system:

macOS 12.6

* Browsers you attempted to reproduce this bug on (the more the merrier): 

n/a

* Does the problem persist after removing "assets/node_modules" and trying again? Yes/no:

n/a

### Actual behavior

warning: undefined attribute "data" for component Phoenix.Component.form/1

When passing a keyword list to the data element of a form:

e.g. `data={[has_changed: !no_changes?(@changeset)]}`

which renders correctly as `<form data-has-changed="false"  ...`

But has a compiler warning.

### Expected behavior

no warning please!

The global prefix `data-` has no warning (e.g. `data-has-changed="false"`), but has a separate issue (will report it separately #2218).

This documentation doesn't mention using the `data` keyword list syntax, so I don't know if it is officially supported, but it is something we're using.
https://hexdocs.pm/phoenix_live_view/0.18.0/js-interop.html#client-server-communication

### PR DESCRIPTION
**Pull request by anmlnath**
resolves #2217

### CODE REVIEW

**Comment by josevalim** [comment]
If we were to merge this, then I think we should also support `aria`. But I am also fine with telling people to use data-* and aria-*.

**Comment by anmlnath** [comment]
added `aria`

**Comment by anmlnath** [comment]
For our use case, we ended up transitioning to `data-*` because we only have a single attribute, but others may have a reason to pass a larger keyword list to `data`.

**Comment by chrismccord** [comment]
We're going to wait on this one. It may make sense in the future to merge, but I'd like to see how common it is in the wild first as folks write more components. Thanks!

**Comment by anmlnath** [comment]
👌🏻  pretty sure we worked around it

**Pull request closed without merging**
