### PR TITLE
Support scroll event

### PR DESCRIPTION
**Pull request by Nitrino**
Add `phx-scroll` binding for handle JavaScript scroll event. 
This is required to implement infinite scrolling or animations when scrolling.

### CODE REVIEW

**Comment by Nitrino** [comment]
@chrismccord What do you think about this feature?
I am now doing an experiment on the implementation of the messenger using LiveView and It was very useful for scrolling the chat

**Comment by chrismccord** [comment]
It's a great feature, but some other things need to land first before we move forward with it, namely pushstate work and changing the handle_event callback to always receive a map with metadata. Thanks!

**Comment by Nitrino** [comment]
Thanks for the feedback. Of course, it will wait.

**Comment by Schultzer** [comment]
We properly want to use https://developer.mozilla.org/en-US/docs/Web/API/Intersection_Observer_API
wdyt?

**Comment by snewcomer** [comment]
This is a great start!  With support for IE11, this feature could be implemented with IntersectionObserver and requestAnimationFrame.  This would require a orchestrating class to detect and setup listeners.  Likely the current solution here would be performant for many use cases, using a combination of these two browser APIs will be faster and more maintainable.

These pkgs are likely overkill but do have an eye for performance.  One path is to create that orchestrating class that calls down to either library.

https://github.com/snewcomer/raf-pool
https://github.com/snewcomer/intersection-observer-admin

**Comment by josevalim** [comment]
Now that we have added `phx-hook`, we believe it is no longer necessary for this to be part of LiveView, as it can be implemented on the client. Thank you!

**Pull request closed without merging**
