### PR TITLE
Allow replies from :handle_event lifecycle hooks

### LINKED ISSUE #2424: Support replies in event lifecycle hooks
The return type for handle_event hooks will become one of:

```elixir
{:cont | :halt, LiveView.Socket.t()}
| {:halt, map(), LiveView.Socket.t()}
```

**Thinking**: Similar to redirecting from `on_mount`, if you want to reply from a hook you must `:halt` the lifecycle stage so that no other hooks are invoked (as they may also try to reply). Dissimilar to redirects, a reply is not required in order to halt.

### PR DESCRIPTION
**Pull request by mcrumm**
Closes #2424

### CODE REVIEW

**Comment by josevalim** [comment]
The biggest question is `:reply` means `:cont` or `:halt`. It probably makes sense to be `:halt` because it effectively means it was handled. But I though but we could also support `{:cont, reply, state} | {:halt, reply, state}` if we want to do both. I am fine either way but raising for consideration.

**Comment by mcrumm** [comment]
@josevalim Thanks! I was unsure at first, too, so I went with what I thought was clearest– returning `{:reply, map, socket}` halts the lifecycle.

Otherwise, if we allow `{:cont, map, socket}` then we need to pick between (I think) last-write-wins and raising if a hook replies when there is already a reply, and neither struck me as better than halting on reply.

**Comment by chrismccord** [comment]
Once replied, you can't reply again, so we'd have to detect this case and raise if we allow it to continue. `{:reply, map, socket}` (with halt) does seem the most clear but it is a little ambiguous. `{:halt, reply, socket}` is better in the sense it is clear that it is halting, but not as clear that it does the reply.

**Comment by mcrumm** [comment]
@chrismccord You're saying naming things is hard? :D

I don't have strong feelings here, but now that it's been discussed I think I like `{:halt, reply, %Socket{}}` most– it keeps consistency with the rest of the callback hook return values and I think we can clarify the rest in the docs. Wdyt?

**Comment by mcrumm** [comment]
Plus `{:halt, reply, socket}` gives us room to add `{:cont, reply, socket}` later if we find a need for it– otherwise we'll have to add a weird third thing.

**Comment by chrismccord** [comment]
`{:halt, reply, socket}` sounds good!

**Comment by josevalim** [comment]
Btw, there is somewhat of a precedent on `{:stop, reason, reply, state}` in GenServer.

**Comment by chrismccord** [comment]
❤️❤️❤️🐥🔥

**Pull request merged**
