### PR TITLE
Adds Composable Hooks

### PR DESCRIPTION
**Pull request by wrren**
Currently, it's only possible to specify one hook association per-element. Repeated uses of `phx-hook` on the same element won't work; only the first will be used. I've run across situations in my own projects where I want to be able to attach utility hooks, such as hooks that send a dismiss event to a component when any other element on the page is clicked, along with more component-specific hooks. This PR addresses that by allowing multiple hooks to be specified as part of a `phx-hook` attribute.

* Hooks can be specified as either a single hook name, as is currently the case, or as a comma-separated list of hook names
* Each hook exists in its own callback object, so multiple hooks operating on the same element won't interfere with eachother if they modify their `this` object.

**Example**

```elixir

def render(assigns) do
    ~L""""
        <div class="editable" phx-hook="editable,dismissable">
            ...
        </div>
    """"
end
```

### CODE REVIEW

**Comment by henrik** [comment]
I've wanted this :thumbsup: Guess the docs should be updated, too.

**Comment by wrren** [comment]
> I've wanted this 👍 Guess the docs should be updated, too.

Just pushed a commit that adds a reference in the `js-interop` documentation 👍

**Comment by dvic** [comment]
Are there any plans to merge this kind of functionality? If not, what is the approach most people use for these kind of 'utility' hooks? Manually calling (common) functions for a few hooks works but it's not ideal. Another idea might be to use a 'middleware' approach on the client side, where the composition of hooks is done. I'd love to hear thoughts of others on this topic. Thanks!

**Comment by chrismccord** [comment]
We will revisit this in the future. Thanks!

**Pull request closed without merging**
