### PR TITLE
Set cache-control no-store on live view responses

### PR DESCRIPTION
**Pull request by jclem**
Hi! 👋 Quick caching fix here, but I also may just be doing something wrong 😆 

Currently, if I have a LiveView-rendered page whose content has changed based on user interaction via LiveView, and I then navigate away from that page and back again via the browser's "Back" button, stale content is rendered.

Adding "no-store" to the "Cache-control" header returned by LiveView-rendered pages resolves this, since it signals to the browser, ["The cache should not store anything about the client request or server response"](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Cache-Control#Cacheability).

Ultimately, I think a better solution is to update "Cache-control" rather than overwriting it entirely (this took me a bit of time to track down), but this may be a good short-term solution (unless there's something else I'm doing wrong w/LiveView that's causing this).

*Update* Looks like Safari doesn’t support “no-store”, yet. 😭

### CODE REVIEW

**Comment by jclem** [comment]
@snewcomer Thank you! It unfortunately works in the browser I develop in (Chrome), but not the one I actually use day-to-day (Safari) 😂

I probably should have opened this as a more general “back button results in stale data” issue. There may be some other solutions, but I haven’t had an opportunity to dive deeper, yet.

**Comment by snewcomer** [comment]
Another note is that `no-store` is a lot more strict so only 200's will be received from the server whereas `no-cache` may get a 304 or 200 (sry if I am saying something we all know).

I can see some cases where having the back button render stale content is desired.  I'm currently working on that issue right now!  But if we are taking about "cheap" small snippets of HTML or JSON, then this might be a good idea.

I'm not totally sure of the answer, so I'll let others make the final say!

**Comment by chrismccord** [comment]
`no-cache` was indeed the desired outcome that `no-store` enables. For safari and other workarounds if "stale" content is concern, you could override the phx-loading css state to block content until the server has mounted and rendered the up-to-state connected content. Thanks!

**Comment by hasmanyguitars** [comment]
> @snewcomer Thank you! It unfortunately works in the browser I develop in (Chrome), but not the one I actually use day-to-day (Safari) 😂
> 
> I probably should have opened this as a more general “back button results in stale data” issue. There may be some other solutions, but I haven’t had an opportunity to dive deeper, yet.

What version of Safari are you using? I was recently testing these headers out (outside of LiveView), and the content was not cached for me on Safari Version 12.1.2 (14607.3.9)

**Pull request merged**
