### PR TITLE
Make `[phx-click]` clickable on iOS

### PR DESCRIPTION
**Pull request by forrestc**
Attempt to solve the same issue as #262, but in a different way. Story described in #262. 

(Note: The compiled `priv/static/phoenix_live_view.js` isn't included in this PR)

### CODE REVIEW

**Comment by jayjun** [comment]
The `cursor: pointer` hack works if `onclick=""` is added to any ancestor too, including `<body>`.

Maybe adding `onclick=""` to every root LiveView is the cleanest solution since we have full control of that element. 100% declarative, no fancy JavaScript.

**Comment by chrismccord** [comment]
Thanks for the PR. We aren't ready to move forward with an iOS specific solution, but folks that need it can use the new JS hooks to do the same approach as this PR. Thanks!

**Comment by jayjun** [comment]
For those looking for a pure markup workaround, add `onclick=""` to `<body>`.

```html
<body onclick="">
```

**Comment by jayjun** [comment]
To those looking for a purely declarative workaround, apply `cursor: pointer` to `phx-click` elements

```css
[phx-click] {
  cursor: pointer;
}
```

and add `onclick=""` to `<body>`.

```html
<body onclick="">
```

You can add `onclick=""` by hand to each `phx-click` element too if you find that less intrusive.

**Comment by tobyjr** [comment]
Thanks @jayjun this totally resolved my issue.

**Comment by tobyjr** [comment]
Actually I just found another potential issue. The phx-click is now resolved by using the onclick="" within the tr. If we assume click goes through to a show page, and on that page you use the browser back button, rather than an in app back, the resulting table is once again no longer clickable.

I'm looking to see if it's cache related.

**Comment by jayjun** [comment]
Now my preferred way is to make all `phx-click` elements into

```html
<button type="button" phx-click="my_event">
  ...
</button>
```

No additional CSS or JavaScript required. No hacks and 100% semantically correct.

**Pull request closed without merging**
